### ISSUE TITLE
API for getting joint velocities from a KinematicState

### ISSUE THREAD

**Issue by aleeper** [moveit/moveit_core#18]
It would be useful to be able to retrieve joint velocities for doing fancy-pants planning. At the simplest level, the velocities could be thrown into a map<string, double>. A more complex method would be to expand the actual JointState class to have velocities. (i.e. Does a simple map allow for multi-variable joints? Do we care?)

Bonus points for a convenience function that does forward time-integration of the state, using a supplied time period and using the velocity values of the state, e.g.
kinematic_state::integrate( start_state, delta_t, distination)

**Comment by sachinchitta** [comment]
there's a setFromDiffIK that uses velocity IK to do this from a given state given a twist. It also includes a nullspace contribution.

**Comment by marioprats** [comment]
Well, the integration is currently done inside the setFromDiffIK but there
was a plan for splitting it into an "integrate" method

**Comment by aleeper** [comment]
@sachinchitta I don't have a twist. I need the current joint velocities so I can estimate the state of the arm at a time slightly in the future (on the order of 10-50 ms). 

I know extrapolation is bad, but it will be better than nothing, and having access to the values received in the sensor_msgs::JointState message will be better than manually computing a finite difference... maybe...

**Comment by isucan** [comment]
I split setDiffFromIK into just the part that computes joint velocities and the part that 'integrates' those joint velocities. That part i guess should be in a separate function as well, which setDiffFromIK calls, and all should be well. 
The integration function is really simple -- just applies fwd Euler method. Since we have f' being constant, it seems to me it is not worth doing any other method. am i missing something?

**Comment by aleeper** [comment]
Forward Euler is all I was going to do...

**Comment by isucan** [comment]
this has been done. For efficient storage, we need #32
