### ISSUE TITLE
rework KinematicState

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_core#32]
make it efficient;

This will happen only after groovy release.

**Comment by acornacorn** [comment]
Some thoughts/notes on this (from an email I sent to Sachin earlier)

some ideas for shrinking KinematicState to speed copying:
- Instead of storing JointState objects, store 
  - a single array of joint_state_values_ (doubles, as many as needed for all joints)
  - a single array of variable_transform_ (matrices, one per joint)
- Store a map from joint name to joint index in the KinematicModel - no need to copy it.
- store an array for mapping joint index to joint_state_values_ offset for each joint.  Store it in the KinematicModel to avoid copying.
- store an array for mapping joint index to variable_transform_ offset for each joint. Store it in the KinematicModel to avoid copying.
- Store mimic requests in the KinematicModel as an array of joint indices.  No need to copy them.
- Array of pointers to JointModel can be stored in the KinematicModel too.
- Instead of storing LinkState objects, just store 2 arrays of matrices:
  - global_link_transform_ for each link
  - global_collision_body_transform_ for each link
- Store a map from link name to link index in the KinematicModel.
- attached bodies can be stored in a map or array of maps inside the KinematicState itself.  Since most links probably do not have attached bodies, an array of pointers to maps might be best.  Possibly keep a range of which are used (min, max) to avoid traversing the whole list when it is empty or mostly empty.

The link/joint hierarchy can be stored in the KinematicModel -- no need to copy it.
- Get rid of these:
    joint_state_vector_  (replaced by arrays described above)
    joint_state_map_    (replaced by name->index map in KinematicModel)
    link_state_vector_   (replaced by arrays described above)
    link_state_map_     (replaced by name->index map in KinematicModel)
    joint_state_group_map_  (I think this info is all in the KinematicModel)

All this means that there are no JointState, LinkState, or JointStateGroup objects stored in the KinematicState for use by clients who reqest them.  I think these can be replaced by small objects which just contain an index and a pointer back to the KinematicState but still support the same operations that are available now.

**Comment by sachinchitta** [comment]
The other thought here might be to move the IK computations into KinematicModel so we have const implementations of it (that are stateless).

**Comment by isucan** [comment]
+1 on all acorn said

**Comment by acornacorn** [comment]
This is more or less implemented now.  Closing.
