### ISSUE TITLE
VariableBounds is uninitialized?

### ISSUE THREAD

**Issue by JeremyZoss** [moveit/moveit_core#88]
I noticed some VERY slow planning in some of my newly-created moveit packages.  The debug logs showed some odd timing (note the 30-sec delay):

```
11:05:48 Solution found in 0.085398 seconds
11:05:48 manipulator: Returning successful solution with 33 states
11:05:48 Running 'Add Time Parameterization'
11:06:22 Motion planner reported a solution path with 33 states
```

I tracked down a config-related issue in my setup-assistant-generated joint_limits.yaml file.  The auto-created file included the following settings for each joint:

```
has_acceleration_limits: true
max_acceleration: 0
```

When I set `has_acceleration_limits: false`, planning worked as expected.

I think the error is not in the Setup Assistant, but in `jointBoundsFromURDF` in `robot_state.cpp`.  In that function, the `VariableBounds` structure is declared, but never initialized.  Structures are not automatically initialized when declared, so their contents are undefined.  My guess is that the `VariableBounds.acceleration_bounded_` flag used in the Setup Assistant is being randomly initialized to `true` in this function, and causing the erroneous `joint_limits.yaml` file.

**Comment by isucan** [comment]
You care correct about the structures if they are interpreted as POD. But VariableBounds has a constructor defined, so it is basically a class with members defaulting to public (not POD).
I think this got fixed, but the issue was probably a conversion between messages and VariableBounds which made acceleration limits uninitialized.
